### ISSUE TITLE
[BUG]Cannot find yaml file in ~/.config/whatsappwebbot/

### ISSUE THREAD

**Issue by Koukotsukan** [rikyiso01/WhatsappWebBot#1]
**Describe the bug**
Cannot find the yaml file in ~/.config/whatsappwebbot/

**To Reproduce**
1. Type ```pip3 install whatsappwebbot``` in the terminal
2. Type ```whatsappwebbot``` or ```sudo whatsappwebbot``` in the terminal

**Expected behavior**
Automatically generate a yaml file in ~/.config/whatsappwebbot/

**Screenshots**
![Image](https://user-images.githubusercontent.com/49346779/107110075-f249f300-687f-11eb-93bf-b572ebc2d891.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version: 10.14.5

**Additional context**
No error occurred during installation.

**Comment by rikyiso01** [comment]
Sorry, I have pushed the README without uploading the new version to pypi
Now it should be fixed
Thank for reporting

**Comment by Koukotsukan** [comment]
Thank you for your useful tool :)
