### ISSUE TITLE
Can the bot read message from another bot?

### ISSUE THREAD

**Issue by deecad** [rikyiso01/WhatsappWebBot#4]
Can the bot read message from another bot?

**Comment by rikyiso01** [comment]
Judging from the Telegram [FAQ](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get) it is not possible:

>  What messages will my bot get?
> 1. All bots, regardless of settings, will receive:
>  All service messages.
>  All messages from private chats with users.
>  All messages from channels where they are a member.
> 2. Bot admins and bots with privacy mode disabled will receive all messages except messages sent by other bots.
